spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxxxxx:3306/framework?useUnicode=true&characterEncoding=utf-8
    username: xxxxxxxx
    password: xxxxxxxx
    druid:
      stat-view-servlet:
        # 开启Druid监控页面
        enabled: true
        # 访问路径
        url-pattern: /druid/*
        # 白名单
        allow: 127.0.0.1
        # 黑名单
        deny:
        # 设置账号密码
        login-username: root
        login-password: 123456
        # 重置按钮
        reset-enable: true
      web-stat-filter:
        # 开启Web应用 URI监控
        enabled: true
        # 拦截路径
        url-pattern: /*
        # 开启Session监控
        session-stat-enable: true
      # 开启SQL监控 SQL防火墙
      filters: stat,wall
      # 开启Spring监控
      aop-patterns: com.zhuqc.framework.*
  flyway:
    # 开启flyway
    enabled: true
    # 数据库非空时，是否执行基线
    baseline-on-migrate: false
    # 执行基线版本号
    baseline-version: 1
    # 校验SQL文件是否存在
    check-location: true
    # SQL文件位置
    locations: classpath:db/migration
    # SQL文件前缀
    sql-migration-prefix: V
    # SQL文件分隔符
    sql-migration-separator: __
    # SQL文件后缀
    sql-migration-suffixes: .sql
    # 记录表名称
    table: flyway_schema_history
    # 目标版本
    target:
mybatis:
  mapper-locations: classpath:sql-mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true